### ISSUE TITLE
"useBatch": false required for NetWeaver ABAP Developer Edition 7.50

### ISSUE THREAD

**Issue by gregorwolf** [hschaefer123/odataexplorer#1]
Dear Holger,

thank you for the great work. I've tried your project against my NetWeaver ABAP Developer Edition 7.50. To make it work I had to set:

```
"useBatch": false
```

in the model configuration. With true I got the error:

> Resource not found for the segment 'ServiceCollection'

for the $batch request.

Hope that tip perhaps helps others.

CU
Gregor

**Comment by tchampag** [comment]
I should have read this first!  I just spent most of yesterday and this morning figuring this out and managed to get find the same resolution.

**Comment by hschaefer123** [comment]
Sorry, will add this to readme. While testing in the cloud using destination, this worked as designed.

I will also set this to default (batch is only relevant for performance stuff and i always set this to false while testing to easier debug network activities.

In this case, there is no big difference and if there are issues with the default sap catalogservices, i will switch this to false by default.

Regards Holger
