### ISSUE TITLE
Deployment on SCP - "no data" - Metadata is loaded

### ISSUE THREAD

**Issue by Zerocool985** [hschaefer123/odataexplorer#4]
Hello Holger,

at first thank you for this. I think this is a great project.

I'm currently trying to deploy this to our SCP Account and have an issue, that no data is shown in the tables. I made the changes that you mentioned

![grafik](https://user-images.githubusercontent.com/38981235/39628724-4092c196-4faa-11e8-8d31-2cd24543951e.png)
![grafik](https://user-images.githubusercontent.com/38981235/39628774-5f38b5a6-4faa-11e8-82cd-5a74ea25f9cd.png)

The metadata seems to be loaded correctly 
![grafik](https://user-images.githubusercontent.com/38981235/39628641-fa51544a-4fa9-11e8-9ecb-bbd3956f1e1e.png)
The response looks like this
![grafik](https://user-images.githubusercontent.com/38981235/39628681-18074cba-4faa-11e8-89b6-18d2b2ebbd82.png)

Do you have an idea what I am doing wrong?

Thank you 

BR
Alex

**Comment by hschaefer123** [comment]
Hi Alex,
i do not see a request reading catalogs! First you need to use the upper left Button Icon to popup the service selector dialog to select the relevant oData service from the scp! After selecting the service you will see the EntitySets on the right side! 

It looks like everything is working as expected!
If you clicked the button, did you saw results?

Maybe if you are using chrome you can filter network on /opu/ to see oData relevant calls only.

Regards Holger

**Comment by Zerocool985** [comment]
Hello Holger, 

this was clearly a user error :). Somehow I didn't get the loading screen in Firefox when I tried to read the catalog. So I thought there has to be an error. In Chrome it works great now.

Just one more thing I noticed was, after deployment as HTML5 App, I had to set
"authenticationMethod": "saml"
in the neo-app.json or else the metadata cannot be read because "No logged-in user"

Anyway thanks again for this app. It is really helpfull in the development process.

Best regards
Alex

**Comment by hschaefer123** [comment]
Hi Alex, 
good to hear that you got it working.

Thanks for the hint with auth method. I am always using it for the demos to make them public available, but for usage inside custom SCP scenario this should be removed. I will add it to the readme.

Regards Holger
